aws/sagemaker-tensorflow-serving-container

- buildspec.yml
buildspec contained an extra comma that causes errors during CD builds.
> fix: remove extra comma in buildspec

- .gitignore
- docker/Dockerfile.eia
- scripts/shared.sh
AmazonEI binary changed name to `amazonei_tensorflow_model_server`, update Dockerfile.eia accordingly.
> fix: update EI binary location

- container/sagemaker/tensorflow-serving.js
- test/integration/local/test_container.py
0.0 was being parsed as a String, not as a float, since 0.0 is falsey.
Oddly, this seems to improve performance, even relative to no parsing changes. I'm running this locally, so it's not a very controlled environment.
This is from `ab -k -n 10000 -c 16 -p test/resources/inputs/test.csv -T 'text/csv' http://localhost:8080/invocations`
```
Document Path:          /invocations
Document Length:        198 bytes
Concurrency Level:      16
Time taken for tests:   15.170 seconds
Complete requests:      10000
Failed requests:        0
Keep-Alive requests:    9908
Total transferred:      3529540 bytes
Total body sent:        2830000
HTML transferred:       1980000 bytes
Requests per second:    659.19 [#/sec] (mean)
Time per request:       24.272 …
```
> Handle zero values correctly

- docker/Dockerfile.eia
- scripts/build.sh
- scripts/shared.sh
- use tmpdir to download and extract ei files
- cleanup ei binary after container build
- decrease container size by removing redundant copy of ei binary
> fix: improve handling of ei binary during builds

- container/sagemaker/tensorflow-serving.js
- test/integration/local/test_container.py
njs has started throwing errors when custom attributes header is not set:
```
*14 js exception: TypeError: cannot get property "match" of undefined
at parse_custom_attributes (tensorflow-serving.js:102)
at make_tfs_uri (tensorflow-serving.js:87)
at ping_tfs_1_11 (tensorflow-serving.js:35)
at ping (tensorflow-serving.js:16)
at main (native)
```
caused by change in behavior from `nginx-module-njs amd64 1.14.2.0.2.7-1~xenial` -> nginx-module-njs amd64 1.16.0.0.3.1-1~xenial` (njs 0.2.7 -> 0.3.1)
> fix: make njs code handle missing custom attributes header

- container/sagemaker/tensorflow-serving.js
- test/integration/local/test_container.py
If "application/jsonlines" is the Accept type, remove newlines. This is so that MultiRecord Batch can join these outputs by newlines and make a parseable JSONLines file.
Apache bench was within noise, for small payloads and for large payloads.
Also, I can't get local testing (with tox or pytest) to work without changing code -- is there more to it than building the images and running tox?
> Add JSONLines accept type

- buildspec.yml
- test/integration/local/conftest.py
- test/integration/local/test_python_service.py
- test/integration/sagemaker/conftest.py
This change also adds back the removed parameters for the local tests. The missing parameters is breaking one of our deployment pipeline
> fix: use p2.xlarge by default in tests

- buildspec.yml
running into throttling limits during deploy build. move the SM tests to release build and only run one test per container during deployment.
> fix: move SageMaker tests to release build

- docker/1.13/Dockerfile.cpu
- docker/1.13/Dockerfile.gpu
> pin versions of all python dependencies

- docker/1.13/Dockerfile.cpu
1. Need to change apt-source type for nginx from ‘xenial’ to ‘bionic’ - minor change, done. 
2. 18.04 already ships with offical python3 repo, however, still trying to install 3.6.6 results in installation of tzdata - which (for some reason) requires user prompt to select timezone, which means automated build will fail.
3. To avoid point 2 above, simply install python3 from official repo, which all works fine. 
Removed the symlink for pip as it is no longer needed in 18.04.
The default pip and pip3 at location /usr/local/bin are just copies:
```
root@a97e70575134:/# whereis pip
pip: /usr/local/bin/pip3.6 /usr/local/bin/pip
root@a97e70575134:/# whereis pip3
pip3: /usr/bin/pip3 /usr/local/bin/pip3 /usr/local/bin/pip3.6
root@a97e70575134:/# which pip …
```
> Update CPU Dockerfile with Ubuntu 18.04 as base

- buildspec.yml
- test/integration/sagemaker/conftest.py
- tox.ini
Add placeholder in test commands for aws-id.
Make regional release tests work for new regions.
> Update no-p2 and no-p3 regions

- container/sagemaker/serve.py
- test/integration/local/test_dynamic_endpoint.py
Currently the `SAGEMAKER_TFS_DEFAULT_MODEL_NAME` environment variable is defaulted to `None`. This will cause problem if `SAGEMAKER_TFS_DEFAULT_MODEL_NAME` is not set when container starts. subprocess will complain NoneType when copying the env_list.
Default `SAGEMAKER_TFS_DEFAULT_MODEL_NAME` to a string 'None' so that hosting can start the container without passing this env var.
> change: default SAGEMAKER_TFS_DEFAULT_MODEL_NAME to string value

- container/sagemaker/serve.py
- test/integration/local/test_dynamic_endpoint.py
- Revert of #76 
- #76 tries to remove the constraints of SAGEMAKER_TFS_DEFAULT_MODEL_NAME, but the /ping check relies on default model.
- We will start a mail thread on the design decision (do healthcheck against TFS model server instead of default model in all cases, or make a logic to do healthcheck against model server instead of default model when multi-model is enabled.)
> fix: require defaul model env var

- docker/1.14/Dockerfile.eia
Issue: Not defining TFS_SHORT_VERSION in Dockerfile causes failure in using sagemaker with dockerfile, unlike versions 1.11-1.13.
Fix:
- Add version number to dockerfile
- Split pip upgrade and install steps to prevent problems with pip
> change: TFS_SHORT_VERSION explicitly defined in dockerfile

- scripts/publish-all.sh
#85 changed `build-all.sh`, but `publish-all.sh` wasn't given the same treatment.
> change: update publish-all.sh to match the versions in build-all.sh

- docker/build_artifacts/sagemaker/tfs_utils.py
Recently, I experienced an issue in deploying the sagemaker serving container. I was getting the following:
```
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:317] Error parsing text-format tensorflow.serving.ModelServerConfig: 8:19: Expected integer, got: .
```
The above error was caused by some hidden folders that were included in the targz process that creates the model.
The issue has been introduced to the following PR: #155. I also see that there is already an open PR for excluding the `code` folder from the `find_model_versions` method (#160).
Instead of excluding explicitly the `code` folder I would prefer filtering by `version.isnumeric()`:
```
".0005".isnumeric() -> False
"code".isnumeric() -> False
"0005".isnumeric() -> True
"5".isnumeric() -> …
```
> Filtering by numeric model versions.

- docker/build_artifacts/sagemaker/serve.py
The following PR enables the `workers` and `threads` configuration in the gunicorn instance inside the sagemaker container.
I'm adding the following env variables `SAGEMAKER_GUNICORN_WORKERS` and `SAGEMAKER_GUNICORN_THREADS` with `1` as default, see [Worker processes](https://docs.gunicorn.org/en/stable/settings.html#worker-processes). This allows to run the instance of gunicorn with a customized worker and threads numbers.
> Extending the serve.py with GUNICORN workers and threads

- docker/1.15/Dockerfile.cpu
After building the container image of version 1.15, I tried to start the container but it did not work. Local tests showed that importing boto3 failed.
```console
$ tox -e py37 -- test/integration/local --framework-version 1.15 -vs                                                                   31.9s  Wed Nov 18 12:29:55 2020
/home/wukann/.cache/pypoetry/virtualenvs/sagemaker-tensorflow-serving-container-v95TaFz_-py3.6/lib/python3.6/site-packages/tox/config/__init__.py:647: UserWarning: conflicting basepython version (set 3.6, should be 3.7) for env 'py37';resolve conflict or set ignore_basepython_conflict
testenv_config.envname,
py37 installed: apipkg==1.5,attrs==20.3.0,boto3==1.16.20,botocore==1.19.20,certifi==2020.11.8,chardet==3.0.4 …
```
> fix: install boto3

- docker/build_artifacts/sagemaker/python_service.py
Tensorflow Inference Container adding one second delay to all inference requests - Latency increases by 1 second
Remove 1s lock for inference
> Remove the 1s lock for inference

- docker/1.13/Dockerfile.gpu
- docker/1.14/Dockerfile.gpu
- docker/1.15/Dockerfile.gpu
- docker/2.0/Dockerfile.gpu
- docker/2.1/Dockerfile.gpu
- docker/build_artifacts/sagemaker/nginx.conf.template
- docker/build_artifacts/sagemaker/python_service.py
- docker/build_artifacts/sagemaker/serve.py
- docker/build_artifacts/sagemaker/tfs_utils.py
Implement new container environment which could expose additional parameters to help user optimize for throughput and fine tune container performance.
The feature that multiple of tensorflow model servers could handle parallel requests coming from different gunicorn workers could be supported in this release. And throughput will be improved based on different parameters tuned. 
Specifically, tunable parameters like`SAGEMAKER_GUNICORN_WORKERS`, `SAGEMAKER_TFS_INSTANCE_COUNT`, `SAGEMAKER_TFS_INTER_OP_PARALLELISM`, `SAGEMAKER_TFS_INTRA_OP_PARALLELISM` and etc.
> feature: expose tunable parameters to support multiple tfs

- docker/build_artifacts/sagemaker/serve.py
AttributeError: 'ServiceManager' object has no attribute '_tfs_grpc_port_range'
Add '_tfs_grpc_port_range' when self._sagemaker_port_range is None
> To fix python sdk repo localmode tfs tests failing issue

- docker/build_artifacts/sagemaker/serve.py
Set OMP_NUM_THREADS default value to 1
*Testing*
Checked the default value inside container
[ec2-user@ip-172-31-6-164 sagemaker-tensorflow-serving-container]$ docker exec -it fd2b0f0428ae /bin/bash
root@fd2b0f0428ae:/# ps aux
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          1  0.0  0.0  20132  3472 ?        Ss   18:46   0:00 /bin/bash /sagemaker/serve
root          6  0.1  0.0  82720 28472 ?        S    18:46   0:00 python3 /sagemaker/serve.py
root          9  0.0  0.0 3265944 52988 ?       Sl   18:46   0:00 tensorflow_model_server --port=9000 --rest_api_port=9001 --model_config_file=/sagema
root        350  0.0  0.0  40136  8028 ?        S    18:46   0:00 nginx: master process /usr/sbin/nginx -c …
> set OMP_NUM_THREADS default value to 1

- docker/build_artifacts/sagemaker/python_service.py
- docker/build_artifacts/sagemaker/serve.py
- some var naming issues
- Refactor naming of variables
- Modify the way port number passing between serve.py and python service
> fix: modify the way port number passing

- .jshintrc
- docker/1.14/Dockerfile.eia
- docker/build_artifacts/sagemaker/multi_model_utils.py
- docker/build_artifacts/sagemaker/nginx.conf.template
- docker/build_artifacts/sagemaker/python_service.py
- docker/build_artifacts/sagemaker/serve.py
- docker/build_artifacts/sagemaker/tensorflowServing.js
- docker/build_artifacts/sagemaker/tfs_utils.py
The njs function `js_include` has been obsolete starting njs `v0.7.1`
http://nginx.org/en/docs/http/ngx_http_js_module.html#js_include
Upgraded the code to use `js_import` in place of `js_include` which requires few changes to the `nginx.conf.template` and the naming of `.js` file. (described below)
- Updated `nginx.conf.template` to use `js_import` instead of `js_include`
- Renamed `tensorflow-serving.js` to `tensorflowServing.js`
- Updated `nginx.conf.template` to use export definitions for the functions
- Fixed pylint errors by passing `utf-8` encoding while opening a file
- Fixed jshint errors by adding `esversion: 6` to `.jshlintrc` file. The `export` statement is available only from es6
- Pull Ubuntu16.04 docker image from ECR …
> Use js_import instead of js_include

- docker/build_artifacts/sagemaker/serve.py
Expose option to set gunicorn logging level. Helpful for debugging gunicorn related errors.
Changes tested in https://github.com/aws/deep-learning-containers/pull/1713
> expose gunicorn logging

- README.md
- docker/build_artifacts/sagemaker/serve.py
Makes the GUnicorn startup timeout configurable via an environment variable. I also updated the readme to include a section that details configurable env vars like this one that do not fit under current sections.
> Add gunicorn timeout

- README.md
- docker/1.15/Dockerfile.gpu
- docker/2.1/Dockerfile.gpu
- docker/build_artifacts/sagemaker/nginx.conf.template
- docker/build_artifacts/sagemaker/serve.py
- test/integration/local/test_nginx_config.py
Adds support for configuring `proxy_read_timeout` in Nginx via an environment variable. This also respects the recently added `SAGEMAKER_GUNICORN_TIMEOUT_SECONDS` to ensure upstream timeouts are avoided.
> Nginx timeouts

- docker/1.15/Dockerfile.gpu
- docker/2.1/Dockerfile.gpu
- docker/build_artifacts/sagemaker/tensorflowServing.js
- test/integration/local/test_container.py
Swaps order on how json requests are processed. This should prevent valid TFS requests from being processed as if its a jsonlines type request.
> Swap order of processing json_request to prevent bad jsonlines request.
