container/sagemaker/nginx.conf.template, container/sagemaker/serve.py, container/sagemaker/tensorflow-serving.js, docker/1.12/Dockerfile.cpu, docker/1.12/Dockerfile.gpu, test/integration/test_container.py
=> add support for TensorFlow Serving 1.12

buildspec.yml, scripts/build.sh, scripts/publish.sh, scripts/shared.sh, test/integration/test_container.py
add buildspec.yml for codebuild
=> add buildspec.yml

buildspec.yml
update buildspec to output `deployments.json` file
this file will be used in our CD deployment pipeline.
=> update buildspec to output deployments.json

scripts/shared.sh
Add a check in shared.sh to print error message if the version cannot be found in the S3 bucket.
=> fix: report error for missing ei version

.gitignore, buildspec.yml, test/integration/sagemaker/conftest.py, test/integration/sagemaker/test_elastic_inference.py, tox.ini
add eia images to release build
=> change: add eia images to release build

scripts/shared.sh
Update the S3 bucket directory and object format as per 04/03/2019 EI TensorFlow Public Release.
=> fix: update EI binary directory

buildspec.yml, scripts/build-all.sh, scripts/publish-all.sh
- add build-all.sh, publish-all.sh scripts to simplify buildspec files (and manual builds)
- fixes potential false positives on codebuild PR builds
=> fix: add build-all.sh, publish-all.sh scripts

README.md
Add documentations to TFS pre/post-processing.
=> doc: add pre-post-processing documentation

README.md, test/integration/local/conftest.py, test/integration/local/test_container.py, test/integration/local/test_python_service.py, test/integration/local/test_tfs_batching.py, tox.ini
Allow users to pass parameters to run local test against a single container.
=> change: allow local test against single container

buildspec.yml, test/integration/local/conftest.py, test/integration/local/test_container.py, tox.ini
=> fix: make tox run any pytest tests

test/integration/sagemaker/test_ei.py
=> fix: fix broken ei tests

docker/1.13/Dockerfile.gpu
Latest available version of TensorRT in Ubuntu Repo is 5.0.2.
Tested by building container locally. 
=> Update CuDNN and NCCL2 versions.

buildspec.yml, docker/1.13/Dockerfile.eia, scripts/build-all.sh, scripts/publish-all.sh
=> feature: add 1.13 EIA containers

test/integration/local/conftest.py, test/integration/local/test_container.py, test/integration/local/test_python_service.py, test/integration/local/test_tfs_batching.py
=> fix: use nvidia-docker for local gpu tests

docker/1.14/Dockerfile.cpu, docker/1.14/Dockerfile.gpu
Add Dockerfile for TFS 1.14.0 both cpu and gpu
=> Add Dockerfile for TFS 1.14

container/sagemaker/python_service.py, test/integration/local/test_dynamic_endpoint.py
Handle GET /models request. List the servables running on model server,
=> feature: list models

container/sagemaker/python_service.py, container/sagemaker/serve.py, test/integration/local/test_dynamic_endpoint.py
update request/response model and url key names
=> fix: update request/response model and url key names

README.md, buildspec.yml, docker/1.13/Dockerfile.cpu, docker/1.13/Dockerfile.eia, docker/1.13/Dockerfile.gpu, docker/1.14/Dockerfile.cpu, docker/1.14/Dockerfile.eia, docker/1.14/Dockerfile.gpu
- asimov has been consuming the asimov branch for DLC release
- diverge between 2 branches is getting larger
- merge asimov branch to master branch
- for Dockerfiles, resolve conflicts following asimov version; for tests, resolve conflicts following master's version
=> change: merge asimov branch to master branch

test/integration/sagemaker/conftest.py
=> change: update instance type region availability

scripts/shared.sh, test/integration/sagemaker/conftest.py, test/integration/sagemaker/util.py, test/perf/create-model.sh
Part of the effort to use the regional endpoint for STS.
=> change: use regional endpoint for STS in builds and tests

docker/1.14/Dockerfile.eia
Binaries need to be updated
Health check update
Upgrading Health cehck
Updating Binaries
=> Updating EI Dockerfile 1.14 with New Health check, and new binaries

container/sagemaker/deep_learning_container.py, docker/1.15/Dockerfile.cpu, docker/1.15/Dockerfile.gpu, docker/1.15/dockerd-entrypoint.py, docker/2.0/Dockerfile.cpu, docker/2.0/Dockerfile.gpu, docker/2.0/dockerd-entrypoint.py
Release TF 1.15 and TF 2.0 dockerfiles, and related build artifacts
Co-authored-by: akhilmehra <akhilrmehra@gmail.com>
Co-authored-by: Kartik Kalamadi <akartsky@gmail.com>
Co-authored-by: ElizaZh <elizazhang087@gmail.com>
Co-authored-by: sboshin <43187008+sboshin@users.noreply.github.com>
=> update: Release TF 1.15 and TF 2.0 dockerfiles

container/sagemaker/__init__.py, container/sagemaker/deep_learning_container.py, container/sagemaker/multi_model_utils.py, container/sagemaker/proxy_client.py, container/sagemaker/python_service.py, container/sagemaker/serve.py, docker/1.15/dockerd-entrypoint.py, docker/2.0/dockerd-entrypoint.py, test/conftest.py, test/integration/local/conftest.py, test/integration/local/test_container.py, test/integration/local/test_multi_model_endpoint.py, test/integration/local/test_python_service.py, test/integration/local/test_tfs_batching.py, test/integration/sagemaker/conftest.py, test/integration/sagemaker/test_ei.py, test/integration/sagemaker/test_tfs.py, test/integration/sagemaker/util.py, test/perf/perftest_endpoint.py, test/resources/examples/test1/inference.py, test/resources/examples/test2/inference.py, test/resources/examples/test3/inference.py, test/resources/examples/test4/inference.py, test/resources/examples/test5/inference.py
=> change: update copyright year in license header

README.md
#107
There is currently no support for pre-/post-processing with multi-model containers, but our documentation doesn't say that.
=> doc: document that pre-/post-processing is not supported with multi-model

docker/1.15/Dockerfile.cpu, docker/1.15/Dockerfile.gpu
=> update 1.15.2 dockerfiles

docker/1.13/Dockerfile.cpu, docker/1.14/Dockerfile.cpu, docker/1.15/Dockerfile.cpu, docker/2.0/Dockerfile.cpu, docker/2.1/Dockerfile.cpu
Remove MME label from serving containers
=> update: Remove multi-model label from CPU containers

docker/1.15/Dockerfile.cpu, docker/1.15/Dockerfile.gpu, docker/2.0/Dockerfile.cpu, docker/2.0/Dockerfile.gpu, docker/2.1/Dockerfile.cpu, docker/2.1/Dockerfile.gpu
Adding of deep_learning_container.py
=> Adding of deep_learning_container.py

docker/1.15/Dockerfile.cpu, docker/1.15/Dockerfile.gpu, docker/2.0/Dockerfile.cpu, docker/2.0/Dockerfile.gpu, docker/2.1/Dockerfile.cpu, docker/2.1/Dockerfile.gpu
Allowing arguments for deep_learning_container.py for tf
=> Allowing arguments for deep_learning_container.py for tf

docker/1.15/Dockerfile.cpu, docker/1.15/Dockerfile.gpu
Sanity test fails with out dated version of awscli and pyyaml
Updating Pyyaml and Awscli version for tf1.15
=> Updating Pyyaml and Awscli version for tf1.15

buildspec.yml, tox.ini
Update tox and buildspecs to test against py37.
=> infra: Test against py37 in buildspec

README.md
Update README for Multi-Model Endpoint information and usage.
=> doc: update README for multi-model endpoint

docker/build_artifacts/sagemaker/tensorflow-serving.js, test/integration/local/test_container.py
* Updated the `tfs_json_request` method of `tensorflow-serving.js` 
=> change: Support multiple Accept types

docker/build_artifacts/sagemaker/tfs_utils.py
``find_models()`` only returns the first model found.
return the method after all models are collected
=> fix: return information of all models

.pylintrc, README.md
Fixes #164
- Fix a broken link in the README
- Disable a new `pylint` warning
=> doc: fix broken link in README

docker/build_artifacts/sagemaker/tensorflow-serving.js, test/integration/sagemaker/util.py
Fix TFS Deploy codebuild issue: js exception: TypeError: cannot get property "trim" of undefined
=> Fix TFS Deploy codebuild issue

test/integration/local/test_container.py
=> Add non safe port set test

docker/build_artifacts/sagemaker/serve.py
=> multi gpu support
